### ISSUE TITLE
PhoneDialer.h not working

### ISSUE THREAD

**Issue by cromanelli** [j-mcnally/PhoneGap-ios-PhoneDialer#2]
Hello, 

I tried to add phoneDialer no my app and i get this error when i try to compile the app. 

PhoneDialer.h:9:9: fatal error: 'PhoneGap/PGPlugin.h' file not found [2]

I am using Cordova 1.5.0 

Thanks for any help.

**Comment by j-mcnally** [comment]
i have not tested with cordova. id look at the structure for where to put plugins. Or the location of the Base plugin header "PGPlugin." has moved.

**Comment by j-mcnally** [comment]
The plugin is update for cordova.
