### ISSUE TITLE
Documentation: PhoneGap.plist vs config.xml?

### ISSUE THREAD

**Issue by plang** [j-mcnally/PhoneGap-ios-PhoneDialer#6]
Hi,

I'm completely new to PhoneGap, so pardon me if I missed something, but according to your doc, we have at some point to:

```
Add "phonedialer" ----> "PhoneDialer" to your plugins mapping in PhoneGap.plist
```

I did that in a file called "config.xml". This might be something new in the latest PhoneGap / Cordova environment?

By the way, thanks for your plugin, it works just fine.

**Comment by j-mcnally** [comment]
mind sending a pull request updating the for cordova?
